version: '3.8'

services:
  guardrails-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - USE_BERT=true
      - FLAGGING_THRESHOLD=0.5
      - BERT_MODEL_NAME=unitary/toxic-bert
    volumes:
      # Optional: Mount for model caching
      - ./models_cache:/home/app/.cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
